#!/bin/bash
apt-get install libgeos-dev
wget https://github.com/matplotlib/basemap/archive/v1.1.0.tar.gz
tar -zxvf v1.1.0.tar.gz
cd geos-3.3.3
export GEOS_DIR=/usr/local
./configure --prefix=$GEOS_DIR
make
make install
